### ISSUE TITLE
Documentation suddenly missing

### ISSUE THREAD

**Issue by Connum** [taufik-nurrohman/text-editor#13]
Somehow, suddenly the documentation links don't work anymore: https://raw.githubusercontent.com/tovic/text-editor/v2.8.5/text-editor/ui

I'm currently actively developing on a project using the text editor, and no I'm pretty stuck, having to implement some custom modals and markdown extensions... Could you please fix the documentation?

**Comment by tovic** [comment]
Download [the version 2.8.5 release](https://github.com/tovic/text-editor/releases/tag/v2.8.5) then read it offline.

**Comment by taufik-nurrohman** [comment]
https://cdn.statically.io/gh/taufik-nurrohman/text-editor/v2.8.5/index.html
