### ISSUE TITLE
bbcode

### ISSUE THREAD

**Issue by redeemerr** [taufik-nurrohman/text-editor#16]
hi is there a plugin for bbcode ?

**Comment by taufik-nurrohman** [comment]
Currently not available. It likely will be available once I have made the generic HTML and Markdown editor.

Current version is focused on the API only, so there is no GUI. It will be available in the future.

HTML, Markdown and BBCode is available in [the older versions](https://github.com/taufik-nurrohman/text-editor/tree/v2.8.5) (it has GUI). But it is no longer maintained.

**Comment by taufik-nurrohman** [comment]
https://cdn.statically.io/gh/taufik-nurrohman/text-editor/v2.8.5/index.html
